config/routes.rb
Rails.application.routes.draw do
  resources :work_logs do
    collection do
      post :import
    end
  end
  
  get '/display/:upload_number', to: 'reports#display'

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :work_logs, dependent: :destroy
  validates_presence_of :job_group
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :employee
  
  def self.generate(employee_ids, upload_number)
    employee_ids.each do |employee_id|
      employee = Employee.find(employee_id)
      employee.work_logs.each do |work_log|
        if work_log.upload_number == upload_number
          if work_log.date.day >= 1 && work_log.date.day <= 15
            pay_period = 1
          else
            pay_period = 2
          end
          report = Report.where(:employee_id => employee.id, :pay_period => pay_period).first_or_create
          report.upload_number = upload_number
          report.pay_month = work_log.date.month
          report.pay_year = work_log.date.year
          if employee.job_group == "A"
            report.amount_paid += work_log.hours_worked * 20
          else
            report.amount_paid += work_log.hours_worked * 30          
          end
          report.save!
        end
      end
    end
  end
end

app/models/work_log.rb
class WorkLog < ApplicationRecord
  belongs_to :employee
  validates_presence_of :date, :hours_worked, :employee_id, :upload_number
  validates :date, uniqueness: { scope: :employee_id }
  
  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    header.collect! { |column_name|
      column_name == "date"? column_name : column_name.gsub!(" ", "_")
    }
    upload_number = Integer(spreadsheet.row(spreadsheet.last_row)[1])
    raise Exception.new("Upload number already exists") if !WorkLog.where(upload_number: upload_number).empty?
    
    employee_ids = []
    
    (2..spreadsheet.last_row - 1).each do |i|
      employee = Employee.find_or_create_by(id: spreadsheet.row(i)[2])
      employee.job_group = spreadsheet.row(i)[3]
      employee.save!
      work_log = new
      work_log.employee_id = Integer(spreadsheet.row(i)[2])
      work_log.date = Date.parse(spreadsheet.row(i)[0])
      work_log.hours_worked = Float(spreadsheet.row(i)[1])
      work_log.upload_number = upload_number
      work_log.save!
      employee_ids.push(spreadsheet.row(i)[2])
    end
    return employee_ids.uniq, upload_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def display
    @reports = Report.where(upload_number: params[:upload_number]).order(:employee_id, :pay_year, :pay_month, :pay_period)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/work_logs_controller.rb
class WorkLogsController < ApplicationController
  def import
    begin
      ids_and_upload_num = WorkLog.import(params[:file])
      Report.generate(ids_and_upload_num[0], ids_and_upload_num[1])
      flash[:success] = "Payroll data imported."
      redirect_to "/display/#{ids_and_upload_num[1]}"
    rescue Exception => e
      if e.class == ActiveRecord::RecordInvalid 
        flash[:error] = "#{e.record.errors.messages.keys[0]} #{e.record.errors.messages.values[0][0]}".capitalize
      else
        flash[:error] = e.message
      end
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_logs_helper.rb
module WorkLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayrollApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payroll_data/index.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<br><br>
<table class="responstable">
  <tr>
    <th><%= t('en.payroll_datum.date') %></th>
    <th><%= t('en.payroll_datum.hours_worked') %></th>
    <th><%= t('en.payroll_datum.employee_id') %></th>
    <th><%= t('en.payroll_datum.job_group') %></th>
    <th><%= t('en.payroll_datum.payroll_report_id') %></th>
    <th><%= t('en.payroll_datum.created_at') %></th>
    <th><%= t('en.payroll_datum.updated_at') %></th>
  </tr>
  <%= render @payroll_data %>
</table>
  

app/views/payroll_datum/payroll_datum.html.erb
<tr>
  <td><%= payroll_datum.date.strftime("%B %e, %Y") %></td>
  <td><%= payroll_datum.hours_worked %></td>
    <!-- t.date "date"
    t.float "hours_worked"
    t.integer "employee_id"
    t.string "job_group"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false -->
  </tr>

app/views/reports/_report.html.erb
<tr>
  <td><%= report.employee_id %></td>
  <td><%= if report.pay_period == 1
            "1/#{report.pay_month}/#{report.pay_year} - 15/#{report.pay_month}/#{report.pay_year}"
          else
          last_day = Date.civil(report.pay_year, report.pay_month, -1)
          "16/#{report.pay_month}/#{report.pay_year} - #{last_day}/#{report.pay_month}/#{report.pay_year}"
          end %>
  </td>
  <td><%= report.amount_paid %></td>
</tr>

app/views/reports/display.html.erb
<% flash.each do |key, value| %>
<div class="<%= flash_class(key) %>">
  <%= value %>
</div>
<% end %>

<h1>Payroll report</h1>

<br><br>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-10">
      <table class="table table-striped ">
        <tr>
          <th><%= t('en.report.employee_id') %></th>
          <th><%= t('en.report.pay_period') %></th>
          <th><%= t('en.report.amount_paid') %></th>
        </tr>
        <% @reports.each do |report| %>
        <%= render partial: "report", locals: { report: report } %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<h1>Payroll Data</h1>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">      
        <h2>Import Data</h2>
      <%= form_tag import_work_logs_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import" %>
      <% end %>
    </div>
  </div>
</div>